### ISSUE TITLE
Fix OTEL collector-gateway config

### ISSUE THREAD

**Issue by david1542** [aspecto-io/opentelemetry-bootcamp#10]
When I run `docker-compose up`, the `collector-gateway` service crashes with the following error:

```bash
 Error: failed to get config: cannot unmarshal the configuration: 1 error(s) decoding: error decoding 'exporters': unknown type: "jaeger" for id: "jaeger" (valid values: [logging otlp otlphttp file kafka prometheus debug opencensus prometheusremotewrite zipkin])
```

After following [this](https://stackoverflow.com/a/77482579/6025929) Stack Overflow answer, the problem has been resolved.

Specifically, the jaegar block:
```yaml
  jaeger:
    endpoint: jaeger:14250
    tls:
      insecure: true
```

has to change to this:
```yaml
  otlp:
    endpoint: jaeger:4317
    tls:
      insecure: true
```

Moreover, in services -> pipelines -> traces -> exporters, the "jaegar" exporter needs to be changed to "otlp".
